all: Buch_der_Weisheit.ifm
	ifm -m -o Buch_der_Weisheit.ps -f ps Buch_der_Weisheit.ifm

items.txt: Buch_der_Weisheit.ifm
	ifm -item -o items.txt Buch_der_Weisheit.ifm

tasks.txt: Buch_der_Weisheit.ifm
	ifm -tasks -o tasks.txt Buch_der_Weisheit.ifm

	


run: Buch_der_Weisheit.ps
	open Buch_der_Weisheit.ps

